### Отправка данных лицеиста
POST localhost:8075/formstudent
Content-Type: application/json

{
  "tgId": "320238701",
  "nickname": "kroexov",
  "name": "Илья Корехов",
  "class": "11А"
}

### Отправка данных выпускника
POST localhost:8075/formgraduate
Content-Type: application/json

{
  "tgId": "320238701",
  "nickname": "kroexov",
  "name": "Илья Корехов",
  "year": "2019",
  "class": "А",
  "cityInfo": "Санкт-Петербург, Москва, Сочи",
  "universityInfo": "ИТМО, МГУ",
  "workInfo": "Программирование, репетиторство",
  "extraInfo": "Люблю бегать и ходить в качалку, знаю много классных мест в СПБ/МСК\nЧасто путешествую, итд итп\nИ ваще я чел еще тот"
}